// <auto-generated />
using System;
using Fundigent.Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fundigent.Blog.Data.Migrations
{
    [DbContext(typeof(FundigentDbContext))]
    [Migration("20200505205939_FundigentDbSeedData1")]
    partial class FundigentDbSeedData1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(140)")
                        .HasMaxLength(140);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92e9bd4c-be55-4c85-9cf4-b3ade63b0562"),
                            CreatedDate = new DateTime(2020, 5, 5, 16, 59, 38, 897, DateTimeKind.Local).AddTicks(1810),
                            ModifiedDate = new DateTime(2020, 5, 5, 16, 59, 38, 897, DateTimeKind.Local).AddTicks(2310),
                            PostId = new Guid("16e9c70e-14bd-411c-ab9a-fba51f2f4610"),
                            Text = "This is an awesome first article!",
                            UserId = new Guid("35a1eba1-35dc-41e7-945b-8eca647f20ba")
                        },
                        new
                        {
                            Id = new Guid("b7b33fe3-7981-4a16-9253-f927c4b901fa"),
                            CreatedDate = new DateTime(2020, 5, 5, 16, 59, 38, 897, DateTimeKind.Local).AddTicks(2870),
                            ModifiedDate = new DateTime(2020, 5, 5, 16, 59, 38, 897, DateTimeKind.Local).AddTicks(2890),
                            PostId = new Guid("16e9c70e-14bd-411c-ab9a-fba51f2f4610"),
                            Text = "I agree with Johnny. This is great!",
                            UserId = new Guid("183fbe51-5258-49b4-9231-55829c18d8c9")
                        });
                });

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlogCategory")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16e9c70e-14bd-411c-ab9a-fba51f2f4610"),
                            BlogCategory = 3,
                            CreatedDate = new DateTime(2020, 5, 5, 16, 59, 38, 879, DateTimeKind.Local).AddTicks(4850),
                            ModifiedDate = new DateTime(2020, 5, 5, 16, 59, 38, 896, DateTimeKind.Local).AddTicks(7340),
                            Text = @"<p>Before we get into more specific details of what makes a web API RESTful, we should probably cover a
                      bit of history. Distributed computing is defined as the communication of one computing system with
                      another computing system where these systems are separated geographically and/or physically using
                      some network. Distributed computing has a long history, going back to the early days of computing and
                      networks. One of the most common ways that we utilize distributed systems today is with HTTP and the internet.</p>

                      <p>But what is REST? Well Representational State Transfer (REST) is an architectural principle or style that
                      says the transfer or modification of data or the state of data should represent the underlying resources
                      of the system providing that data. Additionally, the operations used to modify or transfer that data
                      should be pre-defined and stateless. So, for a web API, the resources that are represented are web
                      resources that map to contextual entities within our system. These contextual entities do not necessarily
                      map to the internal entities in our system, but can be any abstraction that can be named, addressed, or
                      otherwise identified. Also, because this is a Web API, we are using the HTTP protocol. Hyper-Text
                      Transfer Protocol (HTTP) is inherently stateless, so we have that covered and because HTTP also defines
                      a set of methods or verbs, we can use these to satisfy REST’s pre-defined operations requirement.</p>

                      <p>How is REST different from SOAP? Both REST and SOAP solve many of the same problems. It is deeper
                      than JSON vs XML (which can be supported using REST by the way). However, SOAP requires the use of
                      an arbitrary set of self-described operations. It can be argued, that REST provides a cleaner structure for
                      solving the same problems more easily.</p>

                      <p>In my next post, I will get into more of the details of how HTTP enables the creation of RESTful web APIs
                      and some considerations the proper design of your web API.</p> ",
                            Title = "Rest and Web APIs"
                        });
                });

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BlogRole")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83e657b6-a4c2-4dc0-bff1-0059bf96334e"),
                            BlogRole = 2,
                            DisplayName = "JayGregg100",
                            Email = "jaygregg100@gmail.com",
                            FirstName = "Jamison",
                            LastName = "Greggs",
                            Password = "P@ssword1",
                            UserName = "greggsjh"
                        },
                        new
                        {
                            Id = new Guid("35a1eba1-35dc-41e7-945b-8eca647f20ba"),
                            BlogRole = 1,
                            DisplayName = "Here's Johnny!",
                            Email = "johnnyt@test.com",
                            FirstName = "Johnny",
                            LastName = "Test",
                            Password = "P@ssword1",
                            UserName = "jtester"
                        },
                        new
                        {
                            Id = new Guid("183fbe51-5258-49b4-9231-55829c18d8c9"),
                            BlogRole = 1,
                            DisplayName = "Jane",
                            Email = "jane.tester@test.com",
                            FirstName = "Jane",
                            LastName = "Tester",
                            Password = "P@ssword1",
                            UserName = "janetester"
                        });
                });

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.Comment", b =>
                {
                    b.HasOne("Fundigent.Blog.CoreObjects.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fundigent.Blog.CoreObjects.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fundigent.Blog.CoreObjects.Entities.Image", b =>
                {
                    b.HasOne("Fundigent.Blog.CoreObjects.Entities.Post", "Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
